# Generated by Django 5.0.1 on 2025-12-13 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('payments', '0001_initial'),
        ('user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpaymentbill',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_profiles.organizer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rsvp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.rsvp'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tickettype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionoforganizer',
            name='event_bill',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event_bill_transaction', to='payments.eventpaymentbill'),
        ),
    ]
