# Generated by Django 5.0.1 on 2024-01-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billing_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR')], default='INR', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Digital Payment', 'Digital Payment')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TransactionOfOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR')], default='INR', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Digital Payment', 'Digital Payment')], max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default=None, max_length=30, null=True)),
                ('billing_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
            options={
                'verbose_name': 'Transaction of Organizer',
                'verbose_name_plural': 'Transactions of Organizer',
                'ordering': ['-created_at'],
            },
        ),
    ]
