# Generated by Django 5.0.1 on 2026-05-07 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description_html_event_event_date_idx_and_more'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['session_id'], name='txn_session_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='txn_id_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='txn_user_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_status', '-created_at'], name='txn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ticket_type', 'payment_status'], name='txn_ticket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionoforganizer',
            index=models.Index(fields=['event_bill', '-created_at'], name='txn_org_event_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionoforganizer',
            index=models.Index(fields=['payment_status', '-created_at'], name='txn_org_status_idx'),
        ),
    ]
