# Generated by Django 5.0.1 on 2025-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
