# Generated by Django 5.0.1 on 2024-01-24 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tickettype_image_tickettype_stripe_price_id_and_more'),
        ('payments', '0002_transaction_billing_info_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rsvp',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='events.rsvp'),
        ),
    ]
