# Generated by Django 5.0.1 on 2024-01-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tickettype_currency'),
        ('payments', '0003_transaction_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionoforganizer',
            name='event',
        ),
        migrations.CreateModel(
            name='EventPaymentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR')], default='INR', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_event_bill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('has_finished_event', models.BooleanField(blank=True, default=False, null=True)),
                ('has_completed_payment', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
            options={
                'verbose_name': 'Event Payment Bill',
                'verbose_name_plural': 'Event Payment Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transactionoforganizer',
            name='event_bill',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event_bill_transaction', to='payments.eventpaymentbill'),
        ),
    ]
