# Generated by Django 5.0.1 on 2025-11-08 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_has_finished_event_alter_rsvp_ticket_qty_and_more'),
        ('payments', '0003_transaction_session_id'),
        ('user_profiles', '0005_alter_customuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpaymentbill',
            name='user',
        ),
        migrations.AddField(
            model_name='eventpaymentbill',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_profiles.organizer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rsvp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.rsvp'),
        ),
    ]
