# Generated by Django 5.0.1 on 2025-09-20 02:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='ticket_qty',
            field=models.PositiveIntegerField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='total_charge',
            field=models.PositiveIntegerField(default=Decimal('0')),
        ),
    ]
