# Generated by Django 5.0.1 on 2026-05-07 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'is_active', 'date'], name='event_pub_act_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['has_finished_event', 'date'], name='event_finish_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', '-created_at'], name='event_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['event', '-created_at'], name='rsvp_event_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['attendee', '-created_at'], name='rsvp_attendee_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['transaction_id'], name='rsvp_txn_id_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['is_active', 'is_cancelled', 'is_attended'], name='rsvp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['event', 'is_active'], name='rsvp_event_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', '-created_at'], name='tickettype_event_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['stripe_price_id'], name='tickettype_stripe_idx'),
        ),
    ]
