# Generated by Django 5.0.1 on 2025-09-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rsvp_ticket_qty_rsvp_total_charge'),
        ('user_profiles', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_profiles.organizer'),
        ),
    ]
