# Generated by Django 5.0.1 on 2025-11-08 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_finished_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='ticket_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='total_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
