# Generated by Django 5.0.1 on 2025-11-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_has_finished_event_alter_rsvp_ticket_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='events.event'),
        ),
    ]
