# Generated by Django 5.0.1 on 2025-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_rsvp_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
