# Generated by Django 5.0.1 on 2024-01-20 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tickets', models.IntegerField(default=0)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_visits', models.IntegerField(default=0)),
                ('total_visits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.event')),
            ],
            options={
                'verbose_name': 'EventAnalytics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTypeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_sold', models.IntegerField(default=0)),
                ('tickets_remaining', models.IntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.tickettype')),
            ],
            options={
                'verbose_name': 'TicketTypeAnalytics',
                'ordering': ['-created_at'],
            },
        ),
    ]
