# Generated by Django 5.0.1 on 2025-08-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventanalytics',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
        migrations.AddField(
            model_name='tickettypeanalytics',
            name='ticket_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.tickettype'),
        ),
    ]
