# Generated by Django 5.0.1 on 2026-05-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('events', '0003_event_description_html_event_event_date_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventanalytics',
            old_name='tickets_sold',
            new_name='total_attended',
        ),
        migrations.RenameField(
            model_name='eventanalytics',
            old_name='total_tickets',
            new_name='total_rsvps',
        ),
        migrations.RenameField(
            model_name='tickettypeanalytics',
            old_name='tickets_remaining',
            new_name='remaining_quantity',
        ),
        migrations.RenameField(
            model_name='tickettypeanalytics',
            old_name='gross_revenue',
            new_name='total_revenue',
        ),
        migrations.RenameField(
            model_name='tickettypeanalytics',
            old_name='tickets_sold',
            new_name='total_sold',
        ),
        migrations.RemoveField(
            model_name='eventanalytics',
            name='total_visits',
        ),
        migrations.RemoveField(
            model_name='eventanalytics',
            name='unique_visits',
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tickettypeanalytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='eventanalytics',
            index=models.Index(fields=['event'], name='analytics_event_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettypeanalytics',
            index=models.Index(fields=['ticket_type'], name='analytics_ticket_idx'),
        ),
    ]
