"""
Django settings for rsvp project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Site admin info & branding
ADMIN_NAME = config("ADMIN_NAME", default="Rahul Biswas")
ADMIN_PHONE = config("ADMIN_PHONE", default="+91XXXXXXXXXX")
ADMIN_WHATSAPP = config("ADMIN_WHATSAPP", default="https://wa.me/91XXXXXXXXXX")
ADMIN_EMAIL = config("ADMIN_EMAIL", default="rahulbss16@gmail.com")
DEMO_MODE = config("DEMO_MODE", default=True, cast=bool)
SITE_TAGLINE = config("SITE_TAGLINE", default="Sell tickets in 5 minutes. Keep 100% of your money.")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", False)

ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(" ")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party libraries
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "django_celery_results",
    "corsheaders",
    # internal apps
    "events",
    "payments",
    "qr_codes",
    "analytics",
    "communication",
    "user_profiles",
    "support",
    "registration",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rsvp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.media',
                'events.context_processors.site_info',
            ],
        },
    },
]

WSGI_APPLICATION = "rsvp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Redis Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", "redis://localhost:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Session Configuration (Redis-backed for faster cart operations)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('POSTGRES_DB'),
#         'USER': os.getenv('POSTGRES_USER'),
#         'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
#         'HOST': os.getenv('POSTGRES_HOST', 'db'),
#         'PORT': os.getenv('POSTGRES_PORT', '5432'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = 'user_profiles.CustomUser'
USERNAME_FIELD = 'email'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DEFAULT_RENDERER_CLASSES = ("rest_framework.renderers.JSONRenderer",)

if DEBUG:
    DEFAULT_RENDERER_CLASSES += (
        "rest_framework.renderers.BrowsableAPIRenderer",
    )

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
    "SEARCH_PARAM": "search",
    "ORDERING_PARAM": "ordering",
    "EXCEPTION_HANDLER": "rsvp.handlers.custom_exception_handler",
    # Throttling configuration backed by Redis
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "login": "10/minute",
        "signup": "10/minute",
        "payment": "20/minute",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "EventFlow",
    "DESCRIPTION": "EventFlow helps you create events and sell Tickets RSVP events",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
    },
    "SERVE_PUBLIC": False,
    'EXCLUDE_FROM_SCHEMA': [
        'django.contrib.auth.models.User',
    ],
    # 'POSTPROCESSING_HOOKS': [
    #     'drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields',
    # ],
}
    

ROOT_URLCONF = "rsvp.urls"


# stripe config
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET_KEY = config("STRIPE_WEBHOOK_SECRET_KEY")
SITE_URL = config("SITE_URL")


# supabase config
# DEFAULT_FILE_STORAGE = "rsvp.storage.SupabaseStorage"  # Using Django's default file storage instead
# SUPABASE_URL = config("SUPABASE_URL")
# SUPABASE_API_KEY = config("SUPABASE_API_KEY")
# SUPABASE_BUCKET = config("SUPABASE_BUCKET")


# SMTP Mail service config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = config("EMAIL_ACCOUNT")
EMAIL_HOST_PASSWORD = config("EMAIL_PASSWORD")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Celery Config
CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# Celery Task Routes - Separate queues for different task types
CELERY_TASK_ROUTES = {
    'communication.tasks.mail_tasks.*': {'queue': 'emails'},
    'communication.tasks.notification_tasks.*': {'queue': 'emails'},
    '*.heavy_*': {'queue': 'heavy'},
}

# Celery Task Settings
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft limit

# Celery Beat Schedule (for periodic tasks)
CELERY_BEAT_SCHEDULE = {
    'mark-finished-events': {
        'task': 'events.tasks.mark_finished_events',
        'schedule': 3600.0,  # Every hour
    },
    'cleanup-expired-sessions': {
        'task': 'communication.tasks.cleanup_expired_sessions',
        'schedule': 86400.0,  # Daily
    },
}



CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = (config("CORS_ORIGIN_WHITELIST")).split(' ')
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"

DATE_FORMAT = 'F j, Y'
DATETIME_FORMAT = 'F j, Y, g:i a'
SHORT_DATETIME_FORMAT = 'm/d/Y g:i A'

# Important: Disable localization if you want to enforce your format
USE_L10N = False


LOGIN_URL = '/auth/login/'       # your login URL
LOGIN_REDIRECT_URL = '/'         # where to go after login (optional)
LOGOUT_REDIRECT_URL = '/auth/login/'  # where to go after logout