# Generated by Django 5.0.1 on 2024-01-20 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rsvp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='events.rsvp')),
            ],
            options={
                'verbose_name': 'QRCode',
                'verbose_name_plural': 'QRCodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
