# Generated by Django 5.0.1 on 2025-12-13 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_image', models.ImageField(blank=True, default=None, null=True, upload_to='transaction_qr_code/')),
                ('code_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='payments.transaction')),
            ],
            options={
                'verbose_name': 'QRCode',
                'verbose_name_plural': 'QRCodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
