# Generated by Django 5.0.1 on 2024-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='code_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='transaction_qr_code/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
