# Generated by Django 5.0.1 on 2024-01-24 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_rsvp'),
        ('qr_codes', '0002_qrcode_code_image_alter_qrcode_code_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='rsvp',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='transaction',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='payments.transaction'),
        ),
    ]
