# Generated by Django 5.0.1 on 2026-05-08 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_remove_customuser_available_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_roles',
            field=models.ManyToManyField(related_name='users', to='user_profiles.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='user_profiles.role'),
        ),
    ]
