# Generated by Django 5.0.1 on 2026-05-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_customuser_available_roles_customuser_current_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRSVPHistory',
        ),
    ]
